// Generated by Wrangler on Mon May 27 2024 02:00:49 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	NODE_ENV: string;
	DATABASE_URL: string;
	AUTH_SECRET: string;
}
