// Generated by Wrangler on Tue May 28 2024 21:57:56 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types`

interface Env {
	NODE_ENV: string;
	DATABASE_URL: string;
	AUTH_SECRET: string;
}
